version: '3.4'

services:
  pruebacoderlandback:
    image: ${DOCKER_REGISTRY-}pruebaBackendCoderland
    build:
      context: .
      dockerfile: PruebaCoderland/Dockerfile
  postgres-db:
    image: postgres:latest
    restart: always
    container_name: postgressql_db
    environment:
        POSTGRES_DB: ddbbackend
        POSTGRES_USER: Skpow1234
        POSTGRES_PASSWORD: admin123
    # volumes:
    #     - D:/
    ports:
        - 5433:5432